# Generated by Django 5.1.2 on 2024-10-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_model',
            fields=[
                ('employee_id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('leader', models.CharField(null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('grade', models.IntegerField(blank=True, default=None, null=True)),
                ('team_id', models.CharField()),
                ('team_leader', models.CharField(default=None)),
                ('department_id', models.CharField()),
                ('manager_dep', models.CharField(default=None)),
                ('Created_date', models.DateField(default=None)),
            ],
        ),
    ]
