# Generated by Django 5.1.2 on 2025-03-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_model',
            name='email_approve',
        ),
    ]
