# Generated by Django 5.1.2 on 2025-03-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_model_email_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='email_approve',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
