# Generated by Django 5.1.2 on 2025-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_model_email_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_model2',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('date_start', models.DateField()),
                ('date_plan', models.DateField()),
                ('date_finish', models.DateField(blank=True, default=None, null=True)),
                ('employee_id', models.CharField()),
                ('department_id', models.IntegerField(default=None)),
                ('leader', models.CharField(default=None)),
                ('evidence', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('report', models.FileField(blank=True, default=None, null=True, upload_to='files')),
                ('urgent', models.BooleanField(default=False)),
                ('team_id', models.CharField(default=None)),
                ('team_leader', models.CharField(default=None)),
                ('manager_dep', models.CharField(default=None)),
                ('date_create', models.DateField(blank=True, default=None, null=True)),
                ('date_edit', models.DateField(blank=True, default=None, null=True)),
                ('ip_client_create', models.CharField(blank=True, default=None, null=True)),
                ('ip_client_edit', models.CharField(blank=True, default=None, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('sent_email', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('name_old', models.CharField(blank=True, default=None, null=True)),
                ('date_start_old', models.DateField(blank=True, default=None, null=True)),
                ('date_plan_old', models.DateField(blank=True, default=None, null=True)),
                ('date_finish_old', models.DateField(blank=True, default=None, null=True)),
                ('leader_old', models.CharField(blank=True, default=None, null=True)),
                ('evidence_old', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('report_old', models.FileField(blank=True, default=None, null=True, upload_to='files')),
                ('urgent_old', models.BooleanField(default=False)),
                ('date_edit_old', models.DateField(blank=True, default=None, null=True)),
                ('ip_client_edit_old', models.CharField(blank=True, default=None, null=True)),
                ('email_modify', models.IntegerField(blank=True, default=None, null=True)),
                ('infringe', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('approvebyleader', models.BooleanField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('update_progress', models.CharField(blank=True, default=None, max_length=2500, null=True)),
                ('rejectbyleader', models.BooleanField(blank=True, default=None, null=True)),
                ('commentbyleader', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('email_approve', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
