# Generated by Django 5.1.2 on 2025-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_model2'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='progress_old',
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
    ]
