# Generated by Django 5.1.2 on 2025-03-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_model_progress_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='date_approved',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task_model',
            name='date_reject',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
