# Generated by Django 5.1.2 on 2025-03-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_model_date_approved_task_model_date_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='status',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
