# Generated by Django 5.1.2 on 2025-03-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='email_finish',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
