# Generated by Django 5.1.6 on 2025-03-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_model_email_finish'),
    ]

    operations = [
        migrations.CreateModel(
            name='frequency_task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('date_start', models.DateField()),
                ('date_plan', models.DateField()),
                ('date_finish', models.DateField(blank=True, default=None, null=True)),
                ('employee_id', models.CharField()),
                ('department_id', models.IntegerField(default=None)),
                ('leader', models.CharField(default=None)),
                ('evidence', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('report', models.FileField(blank=True, default=None, null=True, upload_to='files')),
                ('urgent', models.BooleanField(default=False)),
                ('team_id', models.CharField(default=None)),
                ('team_leader', models.CharField(default=None)),
                ('manager_dep', models.CharField(default=None)),
                ('date_create', models.DateField(blank=True, default=None, null=True)),
                ('date_edit', models.DateField(blank=True, default=None, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
