# Generated by Django 5.1.6 on 2025-03-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_frequency_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='frequency_task',
            new_name='frequency_task2',
        ),
    ]
