# Generated by Django 5.1.6 on 2025-03-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_rename_frequency_task_frequency_task2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='frequency_task2',
        ),
    ]
