# Generated by Django 5.1.6 on 2025-03-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_frequency_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency_task',
            name='frequency',
            field=models.CharField(default=None),
        ),
    ]
