# Generated by Django 5.1.6 on 2025-03-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_frequency_task_model_delete_frequency_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency_task_model',
            name='status',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
