# Generated by Django 5.1.6 on 2025-03-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_frequency_task_model_delete_frequency_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='frequency',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
