# Generated by Django 5.1.6 on 2025-03-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_frequency_task_model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency_task_model',
            name='date_create_monthly',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='frequency_task_model',
            name='date_create_quarterly',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='frequency_task_model',
            name='date_create_weekly',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='frequency_task_model',
            name='date_create_yearly',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
