# Generated by Django 5.1.6 on 2025-03-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_task_model_frequency'),
        ('task', '0016_frequency_task_model_date_create_monthly_and_more'),
    ]

    operations = [
    ]
