# Generated by Django 5.1.6 on 2025-03-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_merge_20250317_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='urgent_old',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
