# Generated by Django 5.1.7 on 2025-03-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_task_model2_date_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='date_alarm',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
