# Generated by Django 5.1.7 on 2025-03-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_task_model_date_alarm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task_model2',
        ),
    ]
