# Generated by Django 5.1.2 on 2024-10-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transferinfor_model',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_sender', models.CharField()),
                ('trans_title', models.CharField(max_length=500)),
                ('trans_content', models.CharField(max_length=1000)),
                ('date_write', models.DateField()),
                ('trans_receiver', models.CharField(blank=True, default=None, null=True)),
                ('trans_images', models.ImageField(blank=True, default=None, null=True, upload_to='images_trans')),
                ('trans_report', models.FileField(blank=True, default=None, null=True, upload_to='files_trans')),
                ('trans_team_receiver', models.CharField(blank=True, default=None, null=True)),
                ('trans_dept_receiver', models.CharField(blank=True, default=None, null=True)),
                ('ip_client_create', models.CharField(blank=True, default=None, null=True)),
            ],
        ),
    ]
